mysite/curator/urls.py
from django.urls import path
from . import views

app_name = 'curator'

urlpatterns = [
    path('', views.home, name='home'),
    path('price', views.findbyprice, name='price'),
    path('results', views.price_results, name='results'),
    path('model', views.model, name='model'),
    path('ajax/load-models/', views.load_models, name='ajax_load_models')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('curator.urls')),
    path('admin/', admin.site.urls),
]

mysite/curator/models.py
from django.db import models

# Year shouldn't be in foreign key or in chained lists, as users may want to search in range of years
# class Year(models.Model):
#     year = models.IntegerField()

#     def __str__(self):
#         return str(self.year)

class Brand(models.Model):
    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name


class Model(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name




# # Create your models here.
class Ad(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    model = models.ForeignKey(Model, on_delete=models.CASCADE)
    # year = models.ForeignKey(Year, on_delete=models.CASCADE)  # deprecated
    year = models.CharField(max_length=200)
    gov = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    date = models.DateField()  
    kilos = models.CharField(max_length=200)
    pay_type = models.CharField(max_length=200)
    transmission = models.CharField(max_length=200)
    cc = models.CharField(max_length=200, blank=True, null=True)
    chasis = models.CharField(max_length=200, blank=True, null=True)
    features = models.CharField(max_length=500, blank=True, null=True)
    color = models.CharField(max_length=200, blank=True, null=True)
    price = models.IntegerField()
    url = models.URLField(unique=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    imgs = models.CharField(max_length=2000, blank=True, null=True)

    def __str__(self):
        return '{} - {} - {}'.format(self.brand,
                                    self.model,
                                    self.year)




    

mysite/curator/forms.py
from django import forms
from .models import Ad, Model


class PriceForm(forms.Form):
    min_price = forms.CharField(label="Minimum Price", max_length=100)
    max_price = forms.CharField(label="Maximum Price", max_length=100)


# class ModelForm(forms.Form):
#     brands = [(i+1, x) for i, x in enumerate(Ad.objects.values_list('brand', flat=True).distinct())]
#     brand = forms.ChoiceField(label="Brand", widget=forms.Select, choices=brands)

class ModelForm(forms.ModelForm):
    class Meta:
        model = Ad
        fields = ('brand', 'model')
    
    min_year = forms.CharField(label="Minimum Year", max_length=5)
    max_year = forms.CharField(label="Maximum Year", max_length=5)    


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['model'].queryset = Model.objects.none()

        if 'brand_id' in self.data:
            try:
                brand_id = int(self.data.get('brand_id'))
                self.fields['model'].queryset = Model.objects.filter(brand_id=brand_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Modella queryset
        elif self.instance.pk:
            self.fields['model'].queryset = self.instance.brand.model_set.order_by('name')

mysite/curator/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.db import connection
from django.db.models import Avg
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy

from .models import Ad, Model, Brand
from .forms import PriceForm, ModelForm

from sklearn.metrics.pairwise import cosine_similarity

from .preprocessing import score_queried_ads, load_features_index, one_hot_encode_features

import pandas as pd
import json

# Create your views here.
def home(request):
    if request.method == 'POST':
        form = PriceForm(request.POST)
        if form.is_valid():
            request.session["min_price"] = form.cleaned_data['min_price']
            request.session["max_price"] = form.cleaned_data['max_price']
            return HttpResponseRedirect('results')
                        
    else:
        price_form = PriceForm()
        model_form = ModelForm()


    return render(request, 'curator/home.html', {'price_form':price_form,
                                                 'model_form':model_form})

def findbyprice(request):
    """View for user input"""
    if request.method == 'POST':
        form = PriceForm(request.POST)
        if form.is_valid():
            request.session["min_price"] = form.cleaned_data['min_price']
            request.session["max_price"] = form.cleaned_data['max_price']
            return HttpResponseRedirect('results')
                        
    else:
        form = PriceForm()

    return render(request, 'curator/findbyprice.html', {'form':form})

def price_results(request):
    if request.session.has_key("min_price"):
        min_price = request.session["min_price"]
    if request.session.has_key("max_price"):
        max_price = request.session["max_price"]


    query = str(Ad.objects.all().query)
    queried_ads = pd.read_sql_query(query, connection)
    queried_ads.drop_duplicates(subset=['url'], inplace=True)

    mean_prices = queried_ads.groupby(["brand_id", "model_id", "year"]).price.median().reset_index(name="price")
    mean_prices = mean_prices.sort_values(by="year", ascending=False)

    # filter mean_prices 
    mask = (mean_prices.price >= float(min_price)) & (mean_prices.price <= float(max_price))
    mean_prices = mean_prices[mask]

    brands = Brand.objects.all()
    models = Model.objects.all()

    queried_models = []
    for x in mean_prices.itertuples():
        brand = brands.get(id=x.brand_id)
        model = models.get(id=x.model_id)
        queried_models.append({"brand": brand,
                               "model": model,
                               "year": x.year,
                               "price": x.price})

    # TODO: send the queried_models table to the html file
    return render(request, 'curator/results.html', {'queried_models':queried_models,
                                                    })



def model(request):
    """View for results"""
    query = str(Ad.objects.all().query)
    queried_ads = pd.read_sql_query(query, connection)

    print('Before Querying Shape:', queried_ads.shape)

    queried_ads.drop_duplicates(subset=['url'], inplace=True)


    if request.method == "POST":
        data = request.POST.copy()
        brand_id = int(data['brand'])
        model_id = int(data['model'])

        mask = (queried_ads.brand_id == brand_id) & (queried_ads.model_id == model_id) &\
           (queried_ads.year.astype(int) <= int(data['max_year'])) &\
           (queried_ads.year.astype(int) >= int(data['min_year']))

        brand = Brand.objects.filter(id=data['brand'])[0].name
        model = Model.objects.filter(id=data['model'])[0].name

    if request.method == "GET":
        data = request.GET.copy()

        brand_id = Brand.objects.filter(name=data['brand'])[0].id
        model_id = Model.objects.filter(name=data['model'])[0].id

        mask = (queried_ads.brand_id == brand_id) & (queried_ads.model_id == model_id) &\
           (queried_ads.year.astype(int) == int(data['year']))

        brand = data['brand']
        model = data['model']
    

    # print(data["model"], Model.objects.filter(name=data["model"]))
    # model_id = Model.objects.filter(name=data["model"])[0].id
    # brand_id = Brand.objects.filter(name=data["brand"])[0].id

    
    queried_ads = queried_ads[mask]
    

    model = "{}-{}".format(brand, model) # stitch up model name to pass to the template  

    print('Querying Shape:', queried_ads.shape)

    sorted_indices = score_queried_ads(queried_ads)
    queried_ads = queried_ads.iloc[sorted_indices]


    features_index = load_features_index()
    ads_features = one_hot_encode_features(queried_ads.drop(columns=["imgs", "description"]), features_index).replace({1: True, 0: False})

    for _, ad_features in ads_features.iterrows():
        print(ad_features)
        for ad_feature in ad_features:
            print(ad_feature)
        break

    # concat each ad feature into str for card showcase
    ads_features_str = []
    for ad in queried_ads.itertuples():
        try:
            ads_features_str.append(' - '.join(eval(ad.features)))
        except TypeError:
            ads_features_str.append('')

    queried_ads_and_features = [(ad, features_str, ad_features, eval(imgs)[0]) for ad, (_, ad_features), imgs, features_str in zip(queried_ads.itertuples(), ads_features.iterrows(), queried_ads.imgs, ads_features_str)]

    # TODO: find the best ads in a given model query and pass them to the template for rendering
    return render(request, 'curator/model.html', {'queried_ads_and_features': queried_ads_and_features,
                                                  'features': features_index,
                                                  'model': model})


def load_models(request):
    brand_id = request.GET.get('brand_id')
    models = Model.objects.filter(brand_id=brand_id).order_by('name')
    return render(request, 'curator/models_dropdown_list.html', {'models': models})
    

mysite/curator/templates/curator/findbyprice.html
<!DOCTYPE html>
<html> 
<head>
	<style type="text/css">
		body {
			background: #e5e7ee;
		}

		h1 {
			text-align: center;
		}

		fieldset {
			text-align: center;
		}

		legend {
			text-align: center;
		}

		.space {
			height: 150px;
		}




	</style>
	<title>Find By Price</title>
</head>
<body>
	<div class="space">

	</div>
	<h1>Specify a price range</h1>
	<form action="price" method="post">
		<fieldset>
			<legend>Text input</legend>
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Submit">
		</fieldset>
	</form>
</body>
</html>

mysite/curator/templates/curator/home.html
<!doctype html>
<html lang="en">
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<style type="text/css">
		body {
			background: #ffffff;
		}

		h1 { 
			/*flex-grow: 1;*/
			padding-top: 17px;
			text-align: right;
			float: left;
		}

		p {
			/*flex-grow: 1;*/
			text-align: center;
			margin: 5px;
			padding: 5px;
			float: left;
			/*border: solid;*/
		}

		p a {
			text-decoration: none;
		}

		form {
			margin-left: 25%;
			margin-right: 25%;
			width: 50%;
		}


		.container {
			border: 2px dotted black;
			margin: 2px;
			overflow: hidden;
			flex-grow: 1;
		}

		.title {
			display: flex;
			align-items: center;
			justify-content: center;

		}

		.content {
			display: flex;
			flex-direction: column;
		}

		.functions {
			display: flex;
			flex-direction: row;
		}

		.function {
			width: 50%;
		}
			
		.space {
			height: 50px;
		}

		#header {
			margin: 20px;
			margin-left: 5px;
			padding-top: 30px;
			text-align: left;
			border-left: solid 1px;
		}

		#logo-slogan {
			/*margin-left: 5%;
			margin-right: 15%;*/
			width: 80%;
		}


	</style>
	<title>Home Page</title>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="">LO2TA</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  			  <span class="navbar-toggler-icon"></span>
 		 </button>
 		 <div class="collapse navbar-collapse" id="navbarNavDropdown">
 		 	<div class="navbar-nav">
 		 		<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
 		 		<a class="nav-link" href="https://github.com/ahmedsamirio">Github</a>
 		 		<a class="nav-link" href="https://ahmedsamirio.github.io/">Portfolio</a>
 		 	</div>
 		 </div>
	</nav>
	<div class="container-fluid space"></div>
	<div class="container-fluid">
		<div class="container-fluid title">
			<div id="logo-slogan" class="container-fluid title">
				<h1>LO2TA</h1>
				<p id="header">Your honest online car dealer.</p>
			</div>
		</div>
	<div class="container-fluid functions">
		<div class="container-fluid content">
			<p>Search for ads by price</p>
			<form action="price" method="post">
				<fieldset>
					{% csrf_token %}
					{{ price_form.as_table }}
				</fieldset>
				<input type="submit" value="Submit">
			</form>
		</div>
		<div class="container-fluid content">
		{% block content %}
			<p>Search for ads by model</p>
			<form action="model" method="post" id="modelForm" data-models-url="{% url 'curator:ajax_load_models' %}" novalidate>
				{% csrf_token %}
				<table>
					{{ model_form.as_table }}
				</table>
				<input type="submit" value="Submit">
			</form>
		{% endblock %}

			
		</div>
	</div>
	</div>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script>
	$("#id_brand").change(function () {
	  var url = $("#modelForm").attr("data-models-url");  // get the url of the `load_models` view
	  var brandId = $(this).val();  // get the selected brand ID from the HTML input

	  $.ajax({                       // initialize an AJAX request
	    url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
	    data: {
	      'brand_id': brandId       // add the country id to the GET parameters
	    },
	    success: function (data) {   // `data` is the return of the `load_models` view function
	      $("#id_model").html(data);  // replace the contents of the city input with the data that came from the server
	    }
	  });

	});
	</script>
</body>
</html> 

mysite/curator/templates/curator/model.html
<!doctype html>
<html lang="en">
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<style type="text/css">
		th, tr, td {
        	border: 1px solid black;
        	border-collapse: collapse;
        }
        tr {
        	text-align: center;
        }

		.card {
		  flex-direction: row;
		  align-items: center;
		}
		.card img {
		  width: 30%;
		}
	</style>
</head>
<body>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="#">LO2TA</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  			  <span class="navbar-toggler-icon"></span>
 		 </button>
 		 <div class="collapse navbar-collapse" id="navbarNavDropdown">
 		 	<div class="navbar-nav">
 		 		<a class="nav-link" href="../">Home <span class="sr-only">(current)</span></a>
 		 		<a class="nav-link" href="https://github.com/ahmedsamirio">Github</a>
 		 		<a class="nav-link" href="https://ahmedsamirio.github.io/">Portfolio</a>
 		 	</div>
 		 </div>
	</nav>
	<h1 class="text-center">{{ model }} </h1>
	<div class="container">
		{% for ad, features_str, ad_features, img in queried_ads_and_features %}
			<div class="row" style="margin-top:5px">
				<div class="col">
					<div class="card text-center">
						<img src="{{ img }}" alt="Card image cap">
						<div class="card-body">
							<h5 class="card-title">{{ ad.price }} EGP</h5>
							<h6 class="card-subtitle mb-2 text-muted">{{ ad.kilos }} كم</h6>
							<h6 class="card-subtitle mb-2 text-muted">{{ ad.gov }} - {{ ad.city }}</h6>
							<p class="card-text">{{ ad.description }}</p>
							<p class="card-text">{{ features_str }}</p>
							<a href={{ ad.url }} class="card-link">{{ ad.url }}</a>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
<!-- 	<table style="width: 100%">
		<tr>
			<th>Ad</th>
			<th>Year</th>
			<th>Price</th>
			<th>CC</th>
			<th>Transmission</th>
			<th>Kilometers</th>
			{% for feature in features %}
			<th>{{feature}}</th>
			{% endfor %}
		</tr>
		{% for ad, features_str, ad_features, img in queried_ads_and_features %}
		<tr>
			<td><a href={{ad.url}}>Link</a></td>
			<td>{{ad.year}}</td>
			<td>{{ad.price}} EGP</td>
			<td>{{ad.cc}} CC</td>
			<td>{{ad.transmission}}</td>
			<td>{{ad.kilos}} كيلو</td>
			{% for ad_feature in ad_features %}
			{% if ad_feature %}
			<td><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z"/></svg></td>
			{% else %}
			<td><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24"><path d="M24 20.188l-8.315-8.209 8.2-8.282-3.697-3.697-8.212 8.318-8.31-8.203-3.666 3.666 8.321 8.24-8.206 8.313 3.666 3.666 8.237-8.318 8.285 8.203z"/></svg></td>
			{% endif %}
			{% endfor %}
		</tr>
		{% endfor %}
	</table> -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

mysite/curator/templates/curator/models_dropdown_list.html
<option value="">---------</option>
{% for model in models %}
<option value="{{ model.pk }}">{{ model.name }}</option>
{% endfor %}

mysite/curator/templates/curator/results.html
<!DOCTYPE html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<style type="text/css">

	</style>
	<title>
		Result models
	</title>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="#">LO2TA</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  			  <span class="navbar-toggler-icon"></span>
 		 </button>
 		 <div class="collapse navbar-collapse" id="navbarNavDropdown">
 		 	<div class="navbar-nav">
 		 		<a class="nav-link" href="../">Home <span class="sr-only">(current)</span></a>
 		 		<a class="nav-link" href="https://github.com/ahmedsamirio">Github</a>
 		 		<a class="nav-link" href="https://ahmedsamirio.github.io/">Portfolio</a>
 		 	</div>
 		 </div>
	</nav>
	{% for query in queried_models %}
	<div class="card text-center" style="margin-top:5px">
		<a href="{% url 'curator:model' %}?brand={{ query.brand|urlencode }}&model={{ query.model|urlencode }}&year={{ query.year|urlencode }}">{{ query.brand }} - {{ query.model }} - {{ query.year }}</a>
		<p class="card-subtitle mb-2 text-muted">Average Price - {{ query.price }}</p>
	</div>
	{% endfor %}
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>